from __future__ import annotations

import json
import urllib.request
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT_PATH = ROOT / "assets" / "info-card.svg"
USERNAME = "aadithya-vimal"


def fetch_user_data() -> dict[str, str | int]:
    url = f"https://api.github.com/users/{USERNAME}"
    request = urllib.request.Request(
        url,
        headers={
            "Accept": "application/vnd.github+json",
            "User-Agent": "aadithya-vimal-profile-art",
        },
    )
    with urllib.request.urlopen(request, timeout=20) as response:
        payload = json.loads(response.read().decode("utf-8"))

    repos = int(payload.get("public_repos", 0))
    followers = int(payload.get("followers", 0))
    following = int(payload.get("following", 0))
    updated = payload.get("updated_at", "")
    updated_label = "unknown"
    if updated:
        updated_label = datetime.fromisoformat(updated.replace("Z", "+00:00")).strftime("%d %b %Y")
    return {
        "repos": repos,
        "followers": followers,
        "following": following,
        "updated": updated_label,
    }


def count_repo_stars() -> int:
    page = 1
    stars = 0
    while True:
        url = f"https://api.github.com/users/{USERNAME}/repos?per_page=100&page={page}"
        request = urllib.request.Request(
            url,
            headers={
                "Accept": "application/vnd.github+json",
                "User-Agent": "aadithya-vimal-profile-art",
            },
        )
        with urllib.request.urlopen(request, timeout=20) as response:
            repos = json.loads(response.read().decode("utf-8"))
        if not repos:
            break
        stars += sum(int(repo.get("stargazers_count", 0)) for repo in repos)
        page += 1
    return stars


def build_card(data: dict[str, str | int]) -> str:
    generated = datetime.now(timezone.utc).strftime("%d %b %Y")
    return f"""<svg width="490" height="420" viewBox="0 0 490 420" fill="none" xmlns="http://www.w3.org/2000/svg" role="img" aria-labelledby="title desc">
  <title id="title">Aadithya Vimal info card</title>
  <desc id="desc">Terminal style profile card with stack, focus areas, and live metrics. This file is regenerated by script.</desc>
  <defs>
    <linearGradient id="titleGrad" x1="0%" y1="0%" x2="100%" y2="0%">
      <stop offset="0%" stop-color="#22D3EE"/>
      <stop offset="50%" stop-color="#818CF8"/>
      <stop offset="100%" stop-color="#E879F9"/>
    </linearGradient>
  </defs>
  <rect width="490" height="420" rx="18" fill="#050816"/>
  <rect x="1" y="1" width="488" height="418" rx="17" stroke="#1F2937"/>
  <rect x="0" y="0" width="490" height="34" rx="18" fill="#0B1220"/>
  <circle cx="22" cy="17" r="5" fill="#EF4444"/>
  <circle cx="40" cy="17" r="5" fill="#F59E0B"/>
  <circle cx="58" cy="17" r="5" fill="#22C55E"/>
  <text x="245" y="22" fill="url(#titleGrad)" font-family="'Courier New', monospace" font-size="12" text-anchor="middle">Aadithya Vimal — profile</text>

  <text x="24" y="64" fill="#E5E7EB" font-family="'Courier New', monospace" font-size="13">name       : Aadithya Vimal</text>
  <text x="24" y="86" fill="#E5E7EB" font-family="'Courier New', monospace" font-size="13">title      : Full-Stack Developer</text>
  <text x="24" y="108" fill="#E5E7EB" font-family="'Courier New', monospace" font-size="13">focus      : Security, real-time apps, data systems</text>
  <text x="24" y="130" fill="#E5E7EB" font-family="'Courier New', monospace" font-size="13">research   : DevSecOps, telemetry, resilient architecture</text>

  <text x="24" y="170" fill="#67E8F9" font-family="'Courier New', monospace" font-size="12">stack</text>
  <text x="24" y="192" fill="#CBD5E1" font-family="'Courier New', monospace" font-size="12">nextjs  typescript  python  postgres</text>
  <text x="24" y="212" fill="#CBD5E1" font-family="'Courier New', monospace" font-size="12">react   docker      linux   tailwind</text>

  <text x="24" y="252" fill="#67E8F9" font-family="'Courier New', monospace" font-size="12">highlights</text>
  <text x="24" y="274" fill="#CBD5E1" font-family="'Courier New', monospace" font-size="12">- secure system design</text>
  <text x="24" y="294" fill="#CBD5E1" font-family="'Courier New', monospace" font-size="12">- telemetry-driven products</text>
  <text x="24" y="314" fill="#CBD5E1" font-family="'Courier New', monospace" font-size="12">- research-minded shipping</text>

  <text x="24" y="354" fill="#67E8F9" font-family="'Courier New', monospace" font-size="12">github sync</text>
  <text x="24" y="376" fill="#CBD5E1" font-family="'Courier New', monospace" font-size="12">followers: {data["followers"]}   following: {data["following"]}   repos: {data["repos"]}</text>
  <text x="24" y="396" fill="#94A3B8" font-family="'Courier New', monospace" font-size="10">stars: {data["stars"]}   refreshed locally: {generated}   updated: {data["updated"]}</text>
</svg>
"""


def main() -> None:
    data = {
        "repos": "--",
        "followers": "--",
        "following": "--",
        "updated": "unknown",
        "stars": "--",
    }
    try:
        fetched = fetch_user_data()
        fetched["stars"] = count_repo_stars()
        data = fetched
    except Exception:
        pass

    OUTPUT_PATH.write_text(build_card(data), encoding="utf-8")


if __name__ == "__main__":
    main()
